-- ============================================================
-- Seed libreria esercizi — generato da backend/scripts/generate_seed.py
-- Sorgente: docs/reference/FitQuest_Libreria_Esercizi_v1.xlsx (foglio "Esercizi Workout")
-- Totale: 125 esercizi
-- Idempotente: ON CONFLICT DO NOTHING.
-- Non modificare a mano — rigenerare con: python3 backend/scripts/generate_seed.py
-- ============================================================

INSERT INTO exercises (name, muscle_group, category, difficulty) VALUES ('Panca piana bilanciere', 'petto', 'pesi', 2) ON CONFLICT DO NOTHING;
INSERT INTO exercises (name, muscle_group, category, difficulty) VALUES ('Panca piana manubri', 'petto', 'pesi', 2) ON CONFLICT DO NOTHING;
INSERT INTO exercises (name, muscle_group, category, difficulty) VALUES ('Panca inclinata bilanciere', 'petto', 'pesi', 2) ON CONFLICT DO NOTHING;
INSERT INTO exercises (name, muscle_group, category, difficulty) VALUES ('Panca inclinata manubri', 'petto', 'pesi', 2) ON CONFLICT DO NOTHING;
INSERT INTO exercises (name, muscle_group, category, difficulty) VALUES ('Panca declinata bilanciere', 'petto', 'pesi', 2) ON CONFLICT DO NOTHING;
INSERT INTO exercises (name, muscle_group, category, difficulty) VALUES ('Panca declinata manubri', 'petto', 'pesi', 2) ON CONFLICT DO NOTHING;
INSERT INTO exercises (name, muscle_group, category, difficulty) VALUES ('Croci manubri panca piana', 'petto', 'pesi', 1) ON CONFLICT DO NOTHING;
INSERT INTO exercises (name, muscle_group, category, difficulty) VALUES ('Croci manubri panca inclinata', 'petto', 'pesi', 1) ON CONFLICT DO NOTHING;
INSERT INTO exercises (name, muscle_group, category, difficulty) VALUES ('Croci ai cavi', 'petto', 'pesi', 1) ON CONFLICT DO NOTHING;
INSERT INTO exercises (name, muscle_group, category, difficulty) VALUES ('Chest press macchina', 'petto', 'pesi', 1) ON CONFLICT DO NOTHING;
INSERT INTO exercises (name, muscle_group, category, difficulty) VALUES ('Pec deck / Butterfly', 'petto', 'pesi', 1) ON CONFLICT DO NOTHING;
INSERT INTO exercises (name, muscle_group, category, difficulty) VALUES ('Push-up', 'petto', 'corpo_libero', 1) ON CONFLICT DO NOTHING;
INSERT INTO exercises (name, muscle_group, category, difficulty) VALUES ('Push-up inclinati', 'petto', 'corpo_libero', 1) ON CONFLICT DO NOTHING;
INSERT INTO exercises (name, muscle_group, category, difficulty) VALUES ('Dips', 'petto', 'corpo_libero', 2) ON CONFLICT DO NOTHING;
INSERT INTO exercises (name, muscle_group, category, difficulty) VALUES ('Archer push-up', 'petto', 'corpo_libero', 2) ON CONFLICT DO NOTHING;
INSERT INTO exercises (name, muscle_group, category, difficulty) VALUES ('Pseudo planche push-up', 'petto', 'corpo_libero', 3) ON CONFLICT DO NOTHING;
INSERT INTO exercises (name, muscle_group, category, difficulty) VALUES ('Ring push-up', 'petto', 'corpo_libero', 2) ON CONFLICT DO NOTHING;
INSERT INTO exercises (name, muscle_group, category, difficulty) VALUES ('Ring dips', 'petto', 'corpo_libero', 3) ON CONFLICT DO NOTHING;
INSERT INTO exercises (name, muscle_group, category, difficulty) VALUES ('Rematore bilanciere', 'schiena', 'pesi', 2) ON CONFLICT DO NOTHING;
INSERT INTO exercises (name, muscle_group, category, difficulty) VALUES ('Rematore manubrio', 'schiena', 'pesi', 2) ON CONFLICT DO NOTHING;
INSERT INTO exercises (name, muscle_group, category, difficulty) VALUES ('Rematore T-bar', 'schiena', 'pesi', 2) ON CONFLICT DO NOTHING;
INSERT INTO exercises (name, muscle_group, category, difficulty) VALUES ('Rematore ai cavi (pulley basso)', 'schiena', 'pesi', 2) ON CONFLICT DO NOTHING;
INSERT INTO exercises (name, muscle_group, category, difficulty) VALUES ('Lat machine avanti', 'schiena', 'pesi', 2) ON CONFLICT DO NOTHING;
INSERT INTO exercises (name, muscle_group, category, difficulty) VALUES ('Lat machine presa stretta', 'schiena', 'pesi', 2) ON CONFLICT DO NOTHING;
INSERT INTO exercises (name, muscle_group, category, difficulty) VALUES ('Pullover manubrio', 'schiena', 'pesi', 1) ON CONFLICT DO NOTHING;
INSERT INTO exercises (name, muscle_group, category, difficulty) VALUES ('Pulldown ai cavi', 'schiena', 'pesi', 1) ON CONFLICT DO NOTHING;
INSERT INTO exercises (name, muscle_group, category, difficulty) VALUES ('Hyperextension', 'schiena', 'corpo_libero', 1) ON CONFLICT DO NOTHING;
INSERT INTO exercises (name, muscle_group, category, difficulty) VALUES ('Trazioni presa prona', 'schiena', 'corpo_libero', 3) ON CONFLICT DO NOTHING;
INSERT INTO exercises (name, muscle_group, category, difficulty) VALUES ('Trazioni presa supina', 'schiena', 'corpo_libero', 3) ON CONFLICT DO NOTHING;
INSERT INTO exercises (name, muscle_group, category, difficulty) VALUES ('Trazioni presa neutra', 'schiena', 'corpo_libero', 3) ON CONFLICT DO NOTHING;
INSERT INTO exercises (name, muscle_group, category, difficulty) VALUES ('Australian pull-up', 'schiena', 'corpo_libero', 1) ON CONFLICT DO NOTHING;
INSERT INTO exercises (name, muscle_group, category, difficulty) VALUES ('Muscle-up', 'schiena', 'corpo_libero', 3) ON CONFLICT DO NOTHING;
INSERT INTO exercises (name, muscle_group, category, difficulty) VALUES ('Dead hang', 'schiena', 'isometrico', 1) ON CONFLICT DO NOTHING;
INSERT INTO exercises (name, muscle_group, category, difficulty) VALUES ('Front lever raise', 'schiena', 'corpo_libero', 3) ON CONFLICT DO NOTHING;
INSERT INTO exercises (name, muscle_group, category, difficulty) VALUES ('Front lever hold', 'schiena', 'isometrico', 3) ON CONFLICT DO NOTHING;
INSERT INTO exercises (name, muscle_group, category, difficulty) VALUES ('Back lever hold', 'schiena', 'isometrico', 3) ON CONFLICT DO NOTHING;
INSERT INTO exercises (name, muscle_group, category, difficulty) VALUES ('Toes to bar', 'schiena', 'corpo_libero', 2) ON CONFLICT DO NOTHING;
INSERT INTO exercises (name, muscle_group, category, difficulty) VALUES ('Military press bilanciere', 'spalle', 'pesi', 2) ON CONFLICT DO NOTHING;
INSERT INTO exercises (name, muscle_group, category, difficulty) VALUES ('Shoulder press manubri', 'spalle', 'pesi', 2) ON CONFLICT DO NOTHING;
INSERT INTO exercises (name, muscle_group, category, difficulty) VALUES ('Arnold press', 'spalle', 'pesi', 2) ON CONFLICT DO NOTHING;
INSERT INTO exercises (name, muscle_group, category, difficulty) VALUES ('Alzate laterali manubri', 'spalle', 'pesi', 1) ON CONFLICT DO NOTHING;
INSERT INTO exercises (name, muscle_group, category, difficulty) VALUES ('Alzate laterali ai cavi', 'spalle', 'pesi', 1) ON CONFLICT DO NOTHING;
INSERT INTO exercises (name, muscle_group, category, difficulty) VALUES ('Alzate frontali manubri', 'spalle', 'pesi', 1) ON CONFLICT DO NOTHING;
INSERT INTO exercises (name, muscle_group, category, difficulty) VALUES ('Rear delt fly manubri', 'spalle', 'pesi', 1) ON CONFLICT DO NOTHING;
INSERT INTO exercises (name, muscle_group, category, difficulty) VALUES ('Rear delt ai cavi', 'spalle', 'pesi', 1) ON CONFLICT DO NOTHING;
INSERT INTO exercises (name, muscle_group, category, difficulty) VALUES ('Face pull ai cavi', 'spalle', 'pesi', 1) ON CONFLICT DO NOTHING;
INSERT INTO exercises (name, muscle_group, category, difficulty) VALUES ('Tirate al mento', 'spalle', 'pesi', 2) ON CONFLICT DO NOTHING;
INSERT INTO exercises (name, muscle_group, category, difficulty) VALUES ('Shoulder press macchina', 'spalle', 'pesi', 1) ON CONFLICT DO NOTHING;
INSERT INTO exercises (name, muscle_group, category, difficulty) VALUES ('Pike push-up', 'spalle', 'corpo_libero', 2) ON CONFLICT DO NOTHING;
INSERT INTO exercises (name, muscle_group, category, difficulty) VALUES ('Handstand push-up', 'spalle', 'corpo_libero', 3) ON CONFLICT DO NOTHING;
INSERT INTO exercises (name, muscle_group, category, difficulty) VALUES ('Handstand hold', 'spalle', 'isometrico', 3) ON CONFLICT DO NOTHING;
INSERT INTO exercises (name, muscle_group, category, difficulty) VALUES ('L-sit to handstand', 'spalle', 'corpo_libero', 3) ON CONFLICT DO NOTHING;
INSERT INTO exercises (name, muscle_group, category, difficulty) VALUES ('Curl bilanciere dritto', 'braccia', 'pesi', 1) ON CONFLICT DO NOTHING;
INSERT INTO exercises (name, muscle_group, category, difficulty) VALUES ('Curl bilanciere EZ', 'braccia', 'pesi', 1) ON CONFLICT DO NOTHING;
INSERT INTO exercises (name, muscle_group, category, difficulty) VALUES ('Curl manubri alternati', 'braccia', 'pesi', 1) ON CONFLICT DO NOTHING;
INSERT INTO exercises (name, muscle_group, category, difficulty) VALUES ('Curl manubri simultanei', 'braccia', 'pesi', 1) ON CONFLICT DO NOTHING;
INSERT INTO exercises (name, muscle_group, category, difficulty) VALUES ('Curl martello', 'braccia', 'pesi', 1) ON CONFLICT DO NOTHING;
INSERT INTO exercises (name, muscle_group, category, difficulty) VALUES ('Curl concentrato', 'braccia', 'pesi', 1) ON CONFLICT DO NOTHING;
INSERT INTO exercises (name, muscle_group, category, difficulty) VALUES ('Curl ai cavi', 'braccia', 'pesi', 1) ON CONFLICT DO NOTHING;
INSERT INTO exercises (name, muscle_group, category, difficulty) VALUES ('Curl panca Scott', 'braccia', 'pesi', 1) ON CONFLICT DO NOTHING;
INSERT INTO exercises (name, muscle_group, category, difficulty) VALUES ('French press bilanciere', 'braccia', 'pesi', 1) ON CONFLICT DO NOTHING;
INSERT INTO exercises (name, muscle_group, category, difficulty) VALUES ('French press manubri', 'braccia', 'pesi', 1) ON CONFLICT DO NOTHING;
INSERT INTO exercises (name, muscle_group, category, difficulty) VALUES ('Skull crusher', 'braccia', 'pesi', 1) ON CONFLICT DO NOTHING;
INSERT INTO exercises (name, muscle_group, category, difficulty) VALUES ('Tricep pushdown ai cavi', 'braccia', 'pesi', 1) ON CONFLICT DO NOTHING;
INSERT INTO exercises (name, muscle_group, category, difficulty) VALUES ('Tricep pushdown corda', 'braccia', 'pesi', 1) ON CONFLICT DO NOTHING;
INSERT INTO exercises (name, muscle_group, category, difficulty) VALUES ('Kick-back manubri', 'braccia', 'pesi', 1) ON CONFLICT DO NOTHING;
INSERT INTO exercises (name, muscle_group, category, difficulty) VALUES ('Dips stretti', 'braccia', 'corpo_libero', 2) ON CONFLICT DO NOTHING;
INSERT INTO exercises (name, muscle_group, category, difficulty) VALUES ('Diamond push-up', 'braccia', 'corpo_libero', 2) ON CONFLICT DO NOTHING;
INSERT INTO exercises (name, muscle_group, category, difficulty) VALUES ('Chin-up strette', 'braccia', 'corpo_libero', 2) ON CONFLICT DO NOTHING;
INSERT INTO exercises (name, muscle_group, category, difficulty) VALUES ('Tricep dips parallele', 'braccia', 'corpo_libero', 2) ON CONFLICT DO NOTHING;
INSERT INTO exercises (name, muscle_group, category, difficulty) VALUES ('Pseudo planche lean hold', 'braccia', 'isometrico', 2) ON CONFLICT DO NOTHING;
INSERT INTO exercises (name, muscle_group, category, difficulty) VALUES ('Stacco da terra', 'gambe', 'pesi', 3) ON CONFLICT DO NOTHING;
INSERT INTO exercises (name, muscle_group, category, difficulty) VALUES ('Stacco sumo', 'gambe', 'pesi', 3) ON CONFLICT DO NOTHING;
INSERT INTO exercises (name, muscle_group, category, difficulty) VALUES ('Squat bilanciere (back squat)', 'gambe', 'pesi', 3) ON CONFLICT DO NOTHING;
INSERT INTO exercises (name, muscle_group, category, difficulty) VALUES ('Front squat', 'gambe', 'pesi', 3) ON CONFLICT DO NOTHING;
INSERT INTO exercises (name, muscle_group, category, difficulty) VALUES ('Hack squat', 'gambe', 'pesi', 2) ON CONFLICT DO NOTHING;
INSERT INTO exercises (name, muscle_group, category, difficulty) VALUES ('Leg press', 'gambe', 'pesi', 2) ON CONFLICT DO NOTHING;
INSERT INTO exercises (name, muscle_group, category, difficulty) VALUES ('Leg extension', 'gambe', 'pesi', 1) ON CONFLICT DO NOTHING;
INSERT INTO exercises (name, muscle_group, category, difficulty) VALUES ('Leg curl sdraiato', 'gambe', 'pesi', 1) ON CONFLICT DO NOTHING;
INSERT INTO exercises (name, muscle_group, category, difficulty) VALUES ('Leg curl seduto', 'gambe', 'pesi', 1) ON CONFLICT DO NOTHING;
INSERT INTO exercises (name, muscle_group, category, difficulty) VALUES ('Stacco rumeno bilanciere', 'gambe', 'pesi', 2) ON CONFLICT DO NOTHING;
INSERT INTO exercises (name, muscle_group, category, difficulty) VALUES ('Stacco rumeno manubri', 'gambe', 'pesi', 2) ON CONFLICT DO NOTHING;
INSERT INTO exercises (name, muscle_group, category, difficulty) VALUES ('Hip thrust bilanciere', 'gambe', 'pesi', 2) ON CONFLICT DO NOTHING;
INSERT INTO exercises (name, muscle_group, category, difficulty) VALUES ('Affondi bilanciere', 'gambe', 'pesi', 2) ON CONFLICT DO NOTHING;
INSERT INTO exercises (name, muscle_group, category, difficulty) VALUES ('Affondi manubri', 'gambe', 'pesi', 2) ON CONFLICT DO NOTHING;
INSERT INTO exercises (name, muscle_group, category, difficulty) VALUES ('Bulgarian split squat', 'gambe', 'pesi', 2) ON CONFLICT DO NOTHING;
INSERT INTO exercises (name, muscle_group, category, difficulty) VALUES ('Calf raise in piedi', 'gambe', 'pesi', 1) ON CONFLICT DO NOTHING;
INSERT INTO exercises (name, muscle_group, category, difficulty) VALUES ('Calf raise seduto', 'gambe', 'pesi', 1) ON CONFLICT DO NOTHING;
INSERT INTO exercises (name, muscle_group, category, difficulty) VALUES ('Adductor machine', 'gambe', 'pesi', 1) ON CONFLICT DO NOTHING;
INSERT INTO exercises (name, muscle_group, category, difficulty) VALUES ('Abductor machine', 'gambe', 'pesi', 1) ON CONFLICT DO NOTHING;
INSERT INTO exercises (name, muscle_group, category, difficulty) VALUES ('Pistol squat', 'gambe', 'corpo_libero', 3) ON CONFLICT DO NOTHING;
INSERT INTO exercises (name, muscle_group, category, difficulty) VALUES ('Squat a corpo libero', 'gambe', 'corpo_libero', 1) ON CONFLICT DO NOTHING;
INSERT INTO exercises (name, muscle_group, category, difficulty) VALUES ('Affondi a corpo libero', 'gambe', 'corpo_libero', 1) ON CONFLICT DO NOTHING;
INSERT INTO exercises (name, muscle_group, category, difficulty) VALUES ('Step-up', 'gambe', 'corpo_libero', 1) ON CONFLICT DO NOTHING;
INSERT INTO exercises (name, muscle_group, category, difficulty) VALUES ('Jump squat', 'gambe', 'corpo_libero', 2) ON CONFLICT DO NOTHING;
INSERT INTO exercises (name, muscle_group, category, difficulty) VALUES ('Wall sit', 'gambe', 'isometrico', 1) ON CONFLICT DO NOTHING;
INSERT INTO exercises (name, muscle_group, category, difficulty) VALUES ('Crunch', 'core', 'corpo_libero', 1) ON CONFLICT DO NOTHING;
INSERT INTO exercises (name, muscle_group, category, difficulty) VALUES ('Crunch inverso', 'core', 'corpo_libero', 1) ON CONFLICT DO NOTHING;
INSERT INTO exercises (name, muscle_group, category, difficulty) VALUES ('Sit-up', 'core', 'corpo_libero', 1) ON CONFLICT DO NOTHING;
INSERT INTO exercises (name, muscle_group, category, difficulty) VALUES ('Russian twist', 'core', 'corpo_libero', 1) ON CONFLICT DO NOTHING;
INSERT INTO exercises (name, muscle_group, category, difficulty) VALUES ('Mountain climber', 'core', 'corpo_libero', 1) ON CONFLICT DO NOTHING;
INSERT INTO exercises (name, muscle_group, category, difficulty) VALUES ('Bicycle crunch', 'core', 'corpo_libero', 1) ON CONFLICT DO NOTHING;
INSERT INTO exercises (name, muscle_group, category, difficulty) VALUES ('Leg raise a terra', 'core', 'corpo_libero', 1) ON CONFLICT DO NOTHING;
INSERT INTO exercises (name, muscle_group, category, difficulty) VALUES ('Hanging leg raise', 'core', 'corpo_libero', 2) ON CONFLICT DO NOTHING;
INSERT INTO exercises (name, muscle_group, category, difficulty) VALUES ('Knee raise alla sbarra', 'core', 'corpo_libero', 1) ON CONFLICT DO NOTHING;
INSERT INTO exercises (name, muscle_group, category, difficulty) VALUES ('V-up', 'core', 'corpo_libero', 2) ON CONFLICT DO NOTHING;
INSERT INTO exercises (name, muscle_group, category, difficulty) VALUES ('Ab wheel rollout', 'core', 'corpo_libero', 2) ON CONFLICT DO NOTHING;
INSERT INTO exercises (name, muscle_group, category, difficulty) VALUES ('Dragon flag', 'core', 'corpo_libero', 3) ON CONFLICT DO NOTHING;
INSERT INTO exercises (name, muscle_group, category, difficulty) VALUES ('Crunch ai cavi', 'core', 'pesi', 1) ON CONFLICT DO NOTHING;
INSERT INTO exercises (name, muscle_group, category, difficulty) VALUES ('Wood chop ai cavi', 'core', 'pesi', 1) ON CONFLICT DO NOTHING;
INSERT INTO exercises (name, muscle_group, category, difficulty) VALUES ('Pallof press ai cavi', 'core', 'pesi', 1) ON CONFLICT DO NOTHING;
INSERT INTO exercises (name, muscle_group, category, difficulty) VALUES ('Plank', 'core', 'isometrico', 1) ON CONFLICT DO NOTHING;
INSERT INTO exercises (name, muscle_group, category, difficulty) VALUES ('Side plank', 'core', 'isometrico', 1) ON CONFLICT DO NOTHING;
INSERT INTO exercises (name, muscle_group, category, difficulty) VALUES ('L-sit', 'core', 'isometrico', 2) ON CONFLICT DO NOTHING;
INSERT INTO exercises (name, muscle_group, category, difficulty) VALUES ('Corsa', 'cardio', 'cardio', 2) ON CONFLICT DO NOTHING;
INSERT INTO exercises (name, muscle_group, category, difficulty) VALUES ('Camminata veloce', 'cardio', 'cardio', 1) ON CONFLICT DO NOTHING;
INSERT INTO exercises (name, muscle_group, category, difficulty) VALUES ('Bici (cyclette)', 'cardio', 'cardio', 1) ON CONFLICT DO NOTHING;
INSERT INTO exercises (name, muscle_group, category, difficulty) VALUES ('Bici da strada', 'cardio', 'cardio', 2) ON CONFLICT DO NOTHING;
INSERT INTO exercises (name, muscle_group, category, difficulty) VALUES ('Ellittica', 'cardio', 'cardio', 1) ON CONFLICT DO NOTHING;
INSERT INTO exercises (name, muscle_group, category, difficulty) VALUES ('Vogatore (rowing)', 'cardio', 'cardio', 2) ON CONFLICT DO NOTHING;
INSERT INTO exercises (name, muscle_group, category, difficulty) VALUES ('Corda', 'cardio', 'cardio', 1) ON CONFLICT DO NOTHING;
INSERT INTO exercises (name, muscle_group, category, difficulty) VALUES ('Nuoto', 'cardio', 'cardio', 2) ON CONFLICT DO NOTHING;
INSERT INTO exercises (name, muscle_group, category, difficulty) VALUES ('HIIT generico', 'cardio', 'cardio', 2) ON CONFLICT DO NOTHING;
INSERT INTO exercises (name, muscle_group, category, difficulty) VALUES ('StairMaster / scale', 'cardio', 'cardio', 2) ON CONFLICT DO NOTHING;
INSERT INTO exercises (name, muscle_group, category, difficulty) VALUES ('Sprint intervallati', 'cardio', 'cardio', 2) ON CONFLICT DO NOTHING;
